services:
  service:
    build: .
    ports:
      - "10419:3000"
    environment:
      API_URL: ${API_URL}
      NEXT_PUBLIC_SCHOOL_NAME: ${NEXT_PUBLIC_SCHOOL_NAME}
      WCFY_API_URL: ${WCFY_API_URL} # 給下載用的
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_OWNER_EMAIL: ${NEXT_PUBLIC_OWNER_EMAIL}
      REDIS_URL: redis://redis:6379
      CACHE_REDIS_URL: redis://cache-redis:6379
    depends_on:
      redis:
        condition: service_healthy
      cache-redis:
        condition: service_started

  redis:
    image: redis:8-alpine
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - 32mb
      - --maxmemory-policy
      - noeviction
    mem_limit: 64m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cache-redis:
    image: redis:8-alpine
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - 32mb
      - --maxmemory-policy
      - volatile-lru
    mem_limit: 64m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
