services:
  service:
    build: .
    ports:
      - "10419:3000"
    environment:
      API_URL: ${API_URL}
      NEXT_PUBLIC_SCHOOL_NAME: ${NEXT_PUBLIC_SCHOOL_NAME}
      WCFY_API_URL: ${WCFY_API_URL} # 給下載用的
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_OWNER_EMAIL: ${NEXT_PUBLIC_OWNER_EMAIL}
