if ($http_user_agent ~* "(MSIE|Trident/)") {
    return 403;
}

error_page 403 /_rp_cgi/9e7f1216-3c6d-45b4-95c9-1d1a87f8c612_ie_blocked.html;

location = /_rp_cgi/9e7f1216-3c6d-45b4-95c9-1d1a87f8c612_ie_blocked.html {
    default_type text/html;
    return 200 '<!DOCTYPE html>
<html lang="zh-TW">
<head>
<meta charset="UTF-8">
<title>IE 已不支援!</title>
</head>
<body>
<h1 style="background:white;color:black">
Internet Explorer 已經不支援!<br>
請升級您的瀏覽器。<br>
建議使用 <a style="color:blue" href="https://www.mozilla.org/firefox/">Firefox</a>
</h1>
</body>
</html>';
}
